"""Test scripts generated by TestScriptAgent."""
import os
import sys
import pytest

def run_tests(pattern="test_*.py", args=None):
    """Run all tests in this package matching the pattern."""
    if args is None:
        args = []
    test_dir = os.path.dirname(os.path.abspath(__file__))
    return pytest.main([test_dir, "-k", pattern] + args)

if __name__ == "__main__":
    sys.exit(run_tests())
